const data = {
  Character: {
    Avatar:
      "https://img2.finalfantasyxiv.com/f/41b45bea46ace1c769804db581256c57_39e25ac3d737c46452305eefe324372cfc0_96x96.jpg?1671465522",
    ClassJobs: [
      {
        ClassID: 1,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 19,
        Level: 80,
        Name: "gladiator / paladin",
        UnlockedState: {
          ID: 19,
          Name: "Paladin",
        },
      },
      {
        ClassID: 3,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 21,
        Level: 80,
        Name: "marauder / warrior",
        UnlockedState: {
          ID: 21,
          Name: "Warrior",
        },
      },
      {
        ClassID: 32,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 32,
        Level: 80,
        Name: "dark knight / dark knight",
        UnlockedState: {
          ID: 32,
          Name: "Dark Knight",
        },
      },
      {
        ClassID: 37,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 37,
        Level: 80,
        Name: "gunbreaker / gunbreaker",
        UnlockedState: {
          ID: 37,
          Name: "Gunbreaker",
        },
      },
      {
        ClassID: 6,
        ExpLevel: 448800,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5543200,
        IsSpecialised: false,
        JobID: 24,
        Level: 80,
        Name: "conjurer / white mage",
        UnlockedState: {
          ID: 24,
          Name: "White Mage",
        },
      },
      {
        ClassID: 26,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 28,
        Level: 80,
        Name: "arcanist / scholar",
        UnlockedState: {
          ID: 28,
          Name: "Scholar",
        },
      },
      {
        ClassID: 33,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 33,
        Level: 90,
        Name: "astrologian / astrologian",
        UnlockedState: {
          ID: 33,
          Name: "Astrologian",
        },
      },
      {
        ClassID: 40,
        ExpLevel: 216000,
        ExpLevelMax: 2923000,
        ExpLevelTogo: 2707000,
        IsSpecialised: false,
        JobID: 40,
        Level: 70,
        Name: "sage / sage",
        UnlockedState: {
          ID: 40,
          Name: "Sage",
        },
      },
      {
        ClassID: 2,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 20,
        Level: 80,
        Name: "pugilist / monk",
        UnlockedState: {
          ID: 20,
          Name: "Monk",
        },
      },
      {
        ClassID: 4,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 22,
        Level: 80,
        Name: "lancer / dragoon",
        UnlockedState: {
          ID: 22,
          Name: "Dragoon",
        },
      },
      {
        ClassID: 29,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 30,
        Level: 80,
        Name: "rogue / ninja",
        UnlockedState: {
          ID: 30,
          Name: "Ninja",
        },
      },
      {
        ClassID: 34,
        ExpLevel: 8375277,
        ExpLevelMax: 9231000,
        ExpLevelTogo: 855723,
        IsSpecialised: false,
        JobID: 34,
        Level: 86,
        Name: "samurai / samurai",
        UnlockedState: {
          ID: 34,
          Name: "Samurai",
        },
      },
      {
        ClassID: 39,
        ExpLevel: 324000,
        ExpLevelMax: 2923000,
        ExpLevelTogo: 2599000,
        IsSpecialised: false,
        JobID: 39,
        Level: 70,
        Name: "reaper / reaper",
        UnlockedState: {
          ID: 39,
          Name: "Reaper",
        },
      },
      {
        ClassID: 5,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 23,
        Level: 90,
        Name: "archer / bard",
        UnlockedState: {
          ID: 23,
          Name: "Bard",
        },
      },
      {
        ClassID: 31,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 31,
        Level: 80,
        Name: "machinist / machinist",
        UnlockedState: {
          ID: 31,
          Name: "Machinist",
        },
      },
      {
        ClassID: 38,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 38,
        Level: 80,
        Name: "dancer / dancer",
        UnlockedState: {
          ID: 38,
          Name: "Dancer",
        },
      },
      {
        ClassID: 7,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 25,
        Level: 80,
        Name: "thaumaturge / black mage",
        UnlockedState: {
          ID: 25,
          Name: "Black Mage",
        },
      },
      {
        ClassID: 26,
        ExpLevel: 0,
        ExpLevelMax: 5992000,
        ExpLevelTogo: 5992000,
        IsSpecialised: false,
        JobID: 27,
        Level: 80,
        Name: "arcanist / summoner",
        UnlockedState: {
          ID: 27,
          Name: "Summoner",
        },
      },
      {
        ClassID: 35,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 35,
        Level: 90,
        Name: "red mage / red mage",
        UnlockedState: {
          ID: 35,
          Name: "Red Mage",
        },
      },
      {
        ClassID: 36,
        ExpLevel: 0,
        ExpLevelMax: 1387000,
        ExpLevelTogo: 1387000,
        IsSpecialised: false,
        JobID: 36,
        Level: 60,
        Name: "blue mage / blue mage",
        UnlockedState: {
          ID: null,
          Name: "Blue Mage (Limited Job)",
        },
      },
      {
        ClassID: 8,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: true,
        JobID: 8,
        Level: 90,
        Name: "carpenter / carpenter",
        UnlockedState: {
          ID: 8,
          Name: "Carpenter",
        },
      },
      {
        ClassID: 9,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 9,
        Level: 90,
        Name: "blacksmith / blacksmith",
        UnlockedState: {
          ID: 9,
          Name: "Blacksmith",
        },
      },
      {
        ClassID: 10,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 10,
        Level: 90,
        Name: "armorer / armorer",
        UnlockedState: {
          ID: 10,
          Name: "Armorer",
        },
      },
      {
        ClassID: 11,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: true,
        JobID: 11,
        Level: 90,
        Name: "goldsmith / goldsmith",
        UnlockedState: {
          ID: 11,
          Name: "Goldsmith",
        },
      },
      {
        ClassID: 12,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: true,
        JobID: 12,
        Level: 90,
        Name: "leatherworker / leatherworker",
        UnlockedState: {
          ID: 12,
          Name: "Leatherworker",
        },
      },
      {
        ClassID: 13,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 13,
        Level: 90,
        Name: "weaver / weaver",
        UnlockedState: {
          ID: 13,
          Name: "Weaver",
        },
      },
      {
        ClassID: 14,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 14,
        Level: 90,
        Name: "alchemist / alchemist",
        UnlockedState: {
          ID: 14,
          Name: "Alchemist",
        },
      },
      {
        ClassID: 15,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 15,
        Level: 90,
        Name: "culinarian / culinarian",
        UnlockedState: {
          ID: 15,
          Name: "Culinarian",
        },
      },
      {
        ClassID: 16,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 16,
        Level: 90,
        Name: "miner / miner",
        UnlockedState: {
          ID: 16,
          Name: "Miner",
        },
      },
      {
        ClassID: 17,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 17,
        Level: 90,
        Name: "botanist / botanist",
        UnlockedState: {
          ID: 17,
          Name: "Botanist",
        },
      },
      {
        ClassID: 18,
        ExpLevel: 0,
        ExpLevelMax: 0,
        ExpLevelTogo: 0,
        IsSpecialised: false,
        JobID: 18,
        Level: 90,
        Name: "fisher / fisher",
        UnlockedState: {
          ID: 18,
          Name: "Fisher",
        },
      },
    ],
    Name: "Aila Miyu",
    Portrait:
      "https://img2.finalfantasyxiv.com/f/41b45bea46ace1c769804db581256c57_39e25ac3d737c46452305eefe324372cfl0_640x873.jpg?1671465522",
  },
};

export default data;
